package translator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/transos/transos/internal/schema"
)

// PackageMap describes known Linux package mappings for a Windows
// application.
type PackageMap struct {
	AptPackage  string
	FlatpakApp  string
	SnapPackage string
}

// SoftwareMapping contains the migration candidates discovered for a piece
// of source software.
type SoftwareMapping struct {
	SourceName     string
	SourceVersion  string
	AptPackage     string
	FlatpakApp     string
	SnapPackage    string
	Classification string
	Confidence     string
}

// SoftwareCatalog maps normalized Windows application names to Linux
// installation candidates.
//
// This catalog is intentionally conservative. It will become substantially
// richer once the analyzer/planner stages are implemented.
var SoftwareCatalog = map[string]PackageMap{
	"visual studio code": {
		AptPackage: "code",
		FlatpakApp: "com.visualstudio.code",
	},
	"vscode": {
		AptPackage: "code",
		FlatpakApp: "com.visualstudio.code",
	},
	"obsidian": {
		FlatpakApp: "md.obsidian.Obsidian",
	},
	"discord": {
		FlatpakApp: "com.discordapp.Discord",
	},
	"figma": {
		FlatpakApp: "io.figma.Figma",
	},
	"zed": {
		FlatpakApp: "dev.zed.Zed",
	},
	"ollama": {
		AptPackage: "ollama",
	},
	"aria2": {
		AptPackage: "aria2",
	},
	"python": {
		AptPackage: "python3",
	},
	"python 3.10": {
		AptPackage: "python3.10",
	},
	"python 3.12": {
		AptPackage: "python3.12",
	},
	"python 3.13": {
		AptPackage: "python3.13",
	},
	"msys2": {
		AptPackage: "msys2",
	},
}

// AnalyzeSoftware converts canonical software records into deterministic
// Linux migration candidates.
func AnalyzeSoftware(software []schema.Software) []SoftwareMapping {
	results := make([]SoftwareMapping, 0, len(software))

	for _, item := range software {
		name := strings.TrimSpace(item.Name)
		if name == "" {
			continue
		}

		mapping := SoftwareMapping{
			SourceName:     name,
			SourceVersion:  item.Version,
			Classification: schema.ClassificationUnknown,
			Confidence:     "LOW",
		}

		if packageMap, ok := lookupSoftware(name); ok {
			mapping.AptPackage = packageMap.AptPackage
			mapping.FlatpakApp = packageMap.FlatpakApp
			mapping.SnapPackage = packageMap.SnapPackage
			mapping.Classification = schema.ClassificationNativeEquivalent
			mapping.Confidence = "HIGH"
		} else {
			// A known application with no direct mapping remains explicitly
			// classified instead of being silently discarded.
			mapping.Classification = schema.ClassificationManual
			mapping.Confidence = "LOW"
		}

		results = append(results, mapping)
	}

	sort.Slice(results, func(i, j int) bool {
		return strings.ToLower(results[i].SourceName) <
			strings.ToLower(results[j].SourceName)
	})

	return results
}

// lookupSoftware performs deterministic longest-name matching.
//
// Exact matches are preferred. If no exact match exists, the longest catalog
// key contained in the source name is selected.
func lookupSoftware(name string) (PackageMap, bool) {
	normalized := strings.ToLower(strings.TrimSpace(name))

	if mapping, ok := SoftwareCatalog[normalized]; ok {
		return mapping, true
	}

	keys := make([]string, 0, len(SoftwareCatalog))
	for key := range SoftwareCatalog {
		keys = append(keys, key)
	}

	sort.Slice(keys, func(i, j int) bool {
		if len(keys[i]) == len(keys[j]) {
			return keys[i] < keys[j]
		}
		return len(keys[i]) > len(keys[j])
	})

	for _, key := range keys {
		if strings.Contains(normalized, key) {
			return SoftwareCatalog[key], true
		}
	}

	return PackageMap{}, false
}

// GenerateDependencyScript generates a portable Linux dependency installation
// script from canonical software records.
func GenerateDependencyScript(software []schema.Software) string {
	mappings := AnalyzeSoftware(software)

	var aptPackages []string
	var flatpakApps []string
	var snapPackages []string
	var manual []string

	for _, mapping := range mappings {
		if mapping.AptPackage != "" {
			aptPackages = append(aptPackages, mapping.AptPackage)
		}

		if mapping.FlatpakApp != "" {
			flatpakApps = append(flatpakApps, mapping.FlatpakApp)
		}

		if mapping.SnapPackage != "" {
			snapPackages = append(snapPackages, mapping.SnapPackage)
		}

		if mapping.AptPackage == "" &&
			mapping.FlatpakApp == "" &&
			mapping.SnapPackage == "" {
			manual = append(manual, mapping.SourceName)
		}
	}

	aptPackages = uniqueSorted(aptPackages)
	flatpakApps = uniqueSorted(flatpakApps)
	snapPackages = uniqueSorted(snapPackages)
	manual = uniqueSorted(manual)

	var builder strings.Builder

	builder.WriteString("#!/usr/bin/env bash\n")
	builder.WriteString("set -euo pipefail\n\n")
	builder.WriteString("# Generated by TransOS.\n")
	builder.WriteString("# This script installs migration candidates; it does not\n")
	builder.WriteString("# guarantee exact application equivalence.\n\n")

	if len(aptPackages) > 0 {
		builder.WriteString("if command -v apt-get >/dev/null 2>&1; then\n")
		builder.WriteString("    sudo apt-get update\n")
		builder.WriteString("    sudo apt-get install -y")

		for _, pkg := range aptPackages {
			builder.WriteString(" ")
			builder.WriteString(pkg)
		}

		builder.WriteString("\n")
		builder.WriteString("fi\n\n")
	}

	if len(flatpakApps) > 0 {
		builder.WriteString("if command -v flatpak >/dev/null 2>&1; then\n")

		for _, app := range flatpakApps {
			builder.WriteString("    flatpak install -y flathub ")
			builder.WriteString(app)
			builder.WriteString("\n")
		}

		builder.WriteString("fi\n\n")
	}

	if len(snapPackages) > 0 {
		builder.WriteString("if command -v snap >/dev/null 2>&1; then\n")

		for _, pkg := range snapPackages {
			builder.WriteString("    sudo snap install ")
			builder.WriteString(pkg)
			builder.WriteString("\n")
		}

		builder.WriteString("fi\n\n")
	}

	if len(manual) > 0 {
		builder.WriteString("# Manual/unsupported applications:\n")

		for _, app := range manual {
			builder.WriteString("# - ")
			builder.WriteString(app)
			builder.WriteString("\n")
		}

		builder.WriteString("\n")
	}

	builder.WriteString("echo \"TransOS dependency migration step completed.\"\n")

	return builder.String()
}

func uniqueSorted(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	result := make([]string, 0, len(values))

	for _, value := range values {
		if value == "" {
			continue
		}

		if _, exists := seen[value]; exists {
			continue
		}

		seen[value] = struct{}{}
		result = append(result, value)
	}

	sort.Strings(result)

	return result
}

// FormatSoftwareMapping is useful for diagnostics and future CLI reporting.
func FormatSoftwareMapping(mapping SoftwareMapping) string {
	return fmt.Sprintf(
		"%s [%s] → apt=%q flatpak=%q snap=%q",
		mapping.SourceName,
		mapping.Classification,
		mapping.AptPackage,
		mapping.FlatpakApp,
		mapping.SnapPackage,
	)
}
