package injector

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/transos/transos/internal/schema"
	"github.com/transos/transos/internal/translator"
	"github.com/transos/transos/internal/wal"
)

// InjectProfile converts state with WAL transaction logging, shell profile hooks, and dependency script generation
func InjectProfile(profile *schema.ConfigProfile) error {
	configDir := "target_output"

	// 1. Initialize WAL Transaction
	tx, err := wal.NewTransaction(configDir)
	if err != nil {
		return fmt.Errorf("failed to initialize WAL transaction: %w", err)
	}

	// 2. Generate Environment Configuration
	envFilePath := filepath.Join(configDir, "transos_env.conf")
	if err := tx.LogAction(wal.ActionCreateFile, envFilePath, "Writing POSIX environment map"); err != nil {
		return err
	}

	var envSb strings.Builder
	envSb.WriteString("# Generated by TransOS Migration Engine (AST Path Translation Engine Active)\n\n")

	translatedCount := 0
	for k, v := range profile.Environment {
		posixVal := translator.TranslatePathString(v)
		if posixVal != v {
			translatedCount++
		}
		envSb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", k, posixVal))
	}

	if err := os.WriteFile(envFilePath, []byte(envSb.String()), 0644); err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("failed to write environment config: %w", err)
	}

	// 3. Inject Shell Hooks Idempotently (.bashrc / .zshrc)
	injectedShells, err := InjectShellHooks(tx, configDir)
	if err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("shell profile injection failed: %w", err)
	}

	// 4. Generate Deduplicated & Bootstrapped Downloader Script
	scriptFilePath := filepath.Join(configDir, "install_dependencies.sh")
	if err := tx.LogAction(wal.ActionCreateFile, scriptFilePath, "Writing dependency installer script"); err != nil {
		_ = tx.Rollback()
		return err
	}

	aggSoftware := translator.AggregateInstalledSoftware(profile.Registry)
	scriptContent := translator.GenerateDependencyScript(aggSoftware)

	if err := os.WriteFile(scriptFilePath, []byte(scriptContent), 0755); err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("failed to write dependency script: %w", err)
	}

	// 5. Commit WAL Transaction
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("failed to commit WAL transaction: %w", err)
	}

	fmt.Printf("[+] WAL Transaction [%s] COMMITTED safely.\n", tx.TxID)
	fmt.Printf("[+] AST Translator converted %d path variables to POSIX standard.\n", translatedCount)
	fmt.Printf("[+] Injected persistent source hooks into %d shell profiles (skipping existing).\n", injectedShells)
	fmt.Printf("[+] Aggregated %d unique APT packages & %d Flatpak apps (%d unmapped).\n",
		len(aggSoftware.AptPackages), len(aggSoftware.FlatpakApps), len(aggSoftware.Unmapped))
	fmt.Printf("[+] Generated Environment Maps: %s\n", envFilePath)
	fmt.Printf("[+] Generated Downloader Script: %s\n", scriptFilePath)

	return nil
}
