package injector

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/transos/transos/internal/schema"
	"github.com/transos/transos/internal/translator"
	"github.com/transos/transos/internal/wal"
)

// InjectProfile converts state with WAL transaction logging, shell profile hooks, and dependency script generation
func InjectProfile(profile *schema.ConfigProfile) error {
	configDir := "target_output"

	// 1. Initialize WAL Transaction
	tx, err := wal.NewTransaction(configDir)
	if err != nil {
		return fmt.Errorf("failed to initialize WAL transaction: %w", err)
	}

	// 2. Generate Environment Configuration
	envFilePath := filepath.Join(configDir, "transos_env.conf")
	if err := tx.LogAction(wal.ActionCreateFile, envFilePath, "Writing POSIX environment map"); err != nil {
		return err
	}

	var envSb strings.Builder
	envSb.WriteString("# Generated by TransOS Migration Engine (AST Path Translation Engine Active)\n\n")

	translatedCount := 0
	for k, v := range profile.Environment {
		posixVal := translator.TranslatePathString(v)
		if posixVal != v {
			translatedCount++
		}
		envSb.WriteString(fmt.Sprintf("export %s=\"%s\"\n", k, posixVal))
	}

	if err := os.WriteFile(envFilePath, []byte(envSb.String()), 0644); err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("failed to write environment config: %w", err)
	}

	// 3. Inject Auto-Source Hooks into Shell Profiles (.bashrc / .zshrc)
	injectedShells, err := InjectShellHooks(tx, configDir)
	if err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("shell profile injection failed: %w", err)
	}

	// 4. Generate Downloader Script (with Mapped & Unmapped software sections)
	scriptFilePath := filepath.Join(configDir, "install_dependencies.sh")
	if err := tx.LogAction(wal.ActionCreateFile, scriptFilePath, "Writing dependency installer script"); err != nil {
		_ = tx.Rollback()
		return err
	}

	var scriptSb strings.Builder
	scriptSb.WriteString("#!/usr/bin/env bash\n")
	scriptSb.WriteString("# TransOS Automated Dependency & Tool Installer Script\n")
	scriptSb.WriteString("# Generated from Windows Installed Applications Registry\n\n")
	scriptSb.WriteString("echo \"[TransOS] Updating local package databases...\"\n")
	scriptSb.WriteString("sudo apt-get update -y\n\n")
	scriptSb.WriteString("echo \"[TransOS] Installing mapped application dependencies...\"\n\n")

	var unmappedApps []string
	mappedAppsCount := 0

	for k, winAppName := range profile.Registry {
		if strings.HasPrefix(k, "InstalledApp_") {
			if cmd, matched := translator.MapWindowsAppToLinux(winAppName); matched {
				scriptSb.WriteString(fmt.Sprintf("# Mapped from Windows App: %s\n", winAppName))
				scriptSb.WriteString(fmt.Sprintf("%s\n\n", cmd))
				mappedAppsCount++
			} else {
				unmappedApps = append(unmappedApps, winAppName)
			}
		}
	}

	if len(unmappedApps) > 0 {
		scriptSb.WriteString("# =========================================================\n")
		scriptSb.WriteString("# Unmapped Windows Applications (Review for manual install):\n")
		for _, app := range unmappedApps {
			scriptSb.WriteString(fmt.Sprintf("# - %s\n", app))
		}
		scriptSb.WriteString("# =========================================================\n\n")
	}

	scriptSb.WriteString("echo \"[TransOS] All mapped software dependencies installed successfully!\"\n")

	if err := os.WriteFile(scriptFilePath, []byte(scriptSb.String()), 0755); err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("failed to write dependency script: %w", err)
	}

	// 5. Commit WAL Transaction
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("failed to commit WAL transaction: %w", err)
	}

	fmt.Printf("[+] WAL Transaction [%s] COMMITTED safely.\n", tx.TxID)
	fmt.Printf("[+] AST Translator converted %d path variables to POSIX standard.\n", translatedCount)
	fmt.Printf("[+] Injected persistent source hooks into %d shell profiles (.bashrc / .zshrc).\n", injectedShells)
	fmt.Printf("[+] Mapped %d installed packages (%d unmapped noted in script).\n", mappedAppsCount, len(unmappedApps))
	fmt.Printf("[+] Generated Environment Maps: %s\n", envFilePath)
	fmt.Printf("[+] Generated Downloader Script: %s\n", scriptFilePath)

	return nil
}
