package injector

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"github.com/transos/transos/internal/schema"
)

// InjectProfile writes the extracted state into persistent target environment configuration files
func InjectProfile(profile *schema.ConfigProfile) error {
	// Create target config directory simulation
	configDir := "target_output"
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create target output directory: %w", err)
	}

	// Write persistent environment mapping file (simulating /etc/environment or environment.d)
	envFilePath := filepath.Join(configDir, "transos_env.conf")
	var sb strings.Builder
	sb.WriteString("# Generated by TransOS Migration Engine\n")
	for k, v := range profile.Environment {
		// Normalize path primitives during injection
		normalizedVal := filepath.ToSlash(v)
		sb.WriteString(fmt.Sprintf("EXPORT_%s=\"%s\"\n", k, normalizedVal))
	}

	if err := os.WriteFile(envFilePath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write environment config: %w", err)
	}

	fmt.Printf("[+] Successfully wrote persistent environment maps to: %s\n", envFilePath)
	return nil
}